pom.xml
Update common as maven dependency
=> update common as maven dependency

pom.xml
This PR updates built-in app versions
=> Update builtin apps versions

pom.xml
This PR updates the versions of some dependencies in order to remove vulnerabilities.
=> Fix: Update dependency versions to remove vulnerabilities

pom.xml
This reverts commit 613e8ace4f529bf779c583999dbc426a2442fc63.
=> Revert "Fix: Update dependency versions to remove vulnerabilities"

pom.xml
=> add openjfx version

pom.xml
=> changed tomcat version to 8.5.58

.travis.yml, pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/2962
=> Upgrade to Focal(Ubuntu 20.04)

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/2094
=> Add SRT library version

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/4112
=> Update spring version

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/4411
=> Update tomcat version to 8.5.82

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/4520
=> Ffmpeg update

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/5325
=> Update tomcat and jackson-databind

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/5448
=> Update quartz version

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6134
=> Update vertx and push version to remove some vulnerabilities

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6134
=> Update versions to fix vulnerabilities

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6060
=> Add swagger-jaxrs2-jakarta.version 

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6551
=> Upgrade FFmpeg to the latest

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6793
=> Fix CVE-2023-6378

pom.xml
CVE-2024-38821
CVE-2024-22234⁠
CVE-2024-22257
CVE-2023-52428
https://github.com/ant-media/Ant-Media-Server/issues/6794
=> CVE-38821/22234/22257/CVE-2023-52428

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6808
=> Fix CVE-2024-52316: Update Tomcat to 10.1.30 

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6804
=> Update FFmpeg(7.1) and SRT(1.5.3) 

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/6815
=> Update spring-security version 

pom.xml
Update Tomcat version to 10.1.40
=> Update tomcat version to 10.1.40

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/7233
=> Fix CVE-2024-12798

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/7255
=> CVE-2025-4641

pom.xml
=> update protobuf-java version

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/7454
=> Fix CVE-2025-55163

pom.xml
https://github.com/ant-media/Ant-Media-Server/issues/7504
=> Fix Netty version
